<!DOCTYPE HTML>
<html>
<head>
    <title>Demo: <?=$this->encode($title)?></title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?=$this->asset->url('style/main.json')?>">
</head>
<body>
    <header>
        <nav class="horizontal" id="mainmenu" data-hui-touchmenu-id="touchmenu">
            <ul>
                <li><a href="<?=$this->url('index')?>">Home</a></li>
                <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'index'])?>">Index</a></li>
                <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'asset'])?>">Assets</a></li>
                <li>
                    <a href="#">Templates</a>
                    <ul>
                        <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'html'])?>">Html</a></li>
                        <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'sass'])?>">Sass</a></li>
                        <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'haml'])?>">Haml</a></li>
                        <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'htpl'])?>">Htpl</a></li>
                    </ul>
                </li>
                <li><a href="<?=$this->url(null, ['class' => 'index', 'action' => 'args', 'a' => 1, 'b' => 2, 'c' => 3])?>">Args</a></li>
            </ul>
        </nav>
        <nav class="horizontal mobile">
            <ul>
                <li><a href="#" data-hui-touchmenu="#mainmenu"><i class="fa fa-fw fa-ellipsis-v"></i></a></li>
                <li><a href="<?=$this->url('index')?>">Demo</a></li>
                <li><a href="#"><i class="fa fa-fw fa-heart loading-indicator"></i></a></li>
            </ul>
        </nav>
    </header>
    <div role="main">
        <?=$this->content?>
    </div>
    <footer>
        <nav class="horizontal">
            <ul>
                <li><a href="<?=$this->url('bitbucket')?>">Hikari Framework</a></li>
                <li><a href="http://placekitten.com/">Powered by {placekitten}</a></li>
            </ul>
        </nav>
    </footer>
    <script src="//code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="<?=$this->asset->url('script/main.json')?>" async></script>
    <script src="<?=$this->asset->url('script/haml.json')?>" async></script>
</body>
</html>
